apiVersion: v1
kind: Secret
metadata:
  name: tekton-hub-api
type: Opaque
stringData:
  GH_CLIENT_ID: 'a2f510fce5b21c570c4d'
  GH_CLIENT_SECRET: 'afd20e39a934609860f093013a862d9f42c95c21'
  GHE_URL: ''
  GL_CLIENT_ID: ''
  GL_CLIENT_SECRET: ''
  GLE_URL: ''
  BB_CLIENT_ID: ''
  BB_CLIENT_SECRET: ''
  JWT_SIGNING_KEY: ''
  ACCESS_JWT_EXPIRES_IN: ''
  REFRESH_JWT_EXPIRES_IN: ''
  AUTH_BASE_URL: 'http://localhost:1234'
